/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IWKLAY, IWKLAYInterface } from "../IWKLAY";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "to",
        type: "address",
      },
      {
        name: "value",
        type: "uint256",
      },
    ],
    name: "transfer",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [],
    name: "deposit",
    outputs: [],
    payable: true,
    stateMutability: "payable",
    type: "function",
  },
];

export class IWKLAY__factory {
  static readonly abi = _abi;
  static createInterface(): IWKLAYInterface {
    return new utils.Interface(_abi) as IWKLAYInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IWKLAY {
    return new Contract(address, _abi, signerOrProvider) as IWKLAY;
  }
}
