/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface WUSDPoolLibraryInterface extends ethers.utils.Interface {
  functions: {
    "calcMint1t1WUSD(uint256,uint256)": FunctionFragment;
    "calcMintAlgorithmicWUSD(uint256,uint256)": FunctionFragment;
    "calcRecollateralizeWUSDInner(uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
    "calcRedeem1t1WUSD(uint256,uint256)": FunctionFragment;
    "recollateralizeAmount(uint256,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "calcMint1t1WUSD",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calcMintAlgorithmicWUSD",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calcRecollateralizeWUSDInner",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "calcRedeem1t1WUSD",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recollateralizeAmount",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "calcMint1t1WUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calcMintAlgorithmicWUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calcRecollateralizeWUSDInner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calcRedeem1t1WUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recollateralizeAmount",
    data: BytesLike
  ): Result;

  events: {};
}

export class WUSDPoolLibrary extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: WUSDPoolLibraryInterface;

  functions: {
    calcMint1t1WUSD(
      col_price: BigNumberish,
      collateral_amount_d18: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    calcMintAlgorithmicWUSD(
      WMF_price_usd: BigNumberish,
      WMF_amount_d18: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    calcRecollateralizeWUSDInner(
      collateral_amount: BigNumberish,
      col_price: BigNumberish,
      global_collat_value: BigNumberish,
      WUSD_total_supply: BigNumberish,
      global_collateral_ratio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    calcRedeem1t1WUSD(
      col_price_usd: BigNumberish,
      WUSD_amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    recollateralizeAmount(
      total_supply: BigNumberish,
      global_collateral_ratio: BigNumberish,
      global_collat_value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  calcMint1t1WUSD(
    col_price: BigNumberish,
    collateral_amount_d18: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calcMintAlgorithmicWUSD(
    WMF_price_usd: BigNumberish,
    WMF_amount_d18: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calcRecollateralizeWUSDInner(
    collateral_amount: BigNumberish,
    col_price: BigNumberish,
    global_collat_value: BigNumberish,
    WUSD_total_supply: BigNumberish,
    global_collateral_ratio: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  calcRedeem1t1WUSD(
    col_price_usd: BigNumberish,
    WUSD_amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  recollateralizeAmount(
    total_supply: BigNumberish,
    global_collateral_ratio: BigNumberish,
    global_collat_value: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    calcMint1t1WUSD(
      col_price: BigNumberish,
      collateral_amount_d18: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calcMintAlgorithmicWUSD(
      WMF_price_usd: BigNumberish,
      WMF_amount_d18: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calcRecollateralizeWUSDInner(
      collateral_amount: BigNumberish,
      col_price: BigNumberish,
      global_collat_value: BigNumberish,
      WUSD_total_supply: BigNumberish,
      global_collateral_ratio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    calcRedeem1t1WUSD(
      col_price_usd: BigNumberish,
      WUSD_amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recollateralizeAmount(
      total_supply: BigNumberish,
      global_collateral_ratio: BigNumberish,
      global_collat_value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    calcMint1t1WUSD(
      col_price: BigNumberish,
      collateral_amount_d18: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calcMintAlgorithmicWUSD(
      WMF_price_usd: BigNumberish,
      WMF_amount_d18: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calcRecollateralizeWUSDInner(
      collateral_amount: BigNumberish,
      col_price: BigNumberish,
      global_collat_value: BigNumberish,
      WUSD_total_supply: BigNumberish,
      global_collateral_ratio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calcRedeem1t1WUSD(
      col_price_usd: BigNumberish,
      WUSD_amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recollateralizeAmount(
      total_supply: BigNumberish,
      global_collateral_ratio: BigNumberish,
      global_collat_value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    calcMint1t1WUSD(
      col_price: BigNumberish,
      collateral_amount_d18: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calcMintAlgorithmicWUSD(
      WMF_price_usd: BigNumberish,
      WMF_amount_d18: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calcRecollateralizeWUSDInner(
      collateral_amount: BigNumberish,
      col_price: BigNumberish,
      global_collat_value: BigNumberish,
      WUSD_total_supply: BigNumberish,
      global_collateral_ratio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calcRedeem1t1WUSD(
      col_price_usd: BigNumberish,
      WUSD_amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    recollateralizeAmount(
      total_supply: BigNumberish,
      global_collateral_ratio: BigNumberish,
      global_collat_value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
